language: go
go:
  - "1.11.1"

services:
  - docker

env:
  - GO111MODULE=on

install: true

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: make test
    - stage: build
      name: "Build reception"
      script: docker build -f ./Dockerfile_reception -t italolelis/reception:$TRAVIS_COMMIT .
    - name: "Build barista"
      script: docker build -f ./Dockerfile_barista -t italolelis/barista:$TRAVIS_COMMIT .
    - stage: deploy
      name: "Deploy to reception DockerHub"
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push italolelis/reception:$TRAVIS_COMMIT
    - name: "Deploy to barista DockerHub"
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push italolelis/barista:$TRAVIS_COMMIT
