version: '3'
services:

    reception:
        build: 
            context: "./"
            dockerfile: "./Dockerfile_reception"
        ports:
            - '9010:8080'
        environment:
            LOG_LEVEL: debug
            DATABASE_DSN: postgres://coffee:qwerty123@reception_db/reception?sslmode=disable

    reception_db:
        image: postgres:9.6
        ports:
            - '5432:5432'
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: coffee
            POSTGRES_PASSWORD: qwerty123
            POSTGRES_DB: reception

    payments:
        image: rodolpheche/wiremock
        ports:
            - '8080'
        volumes:
            - ./payments:/home/wiremock/mappings
