version: '3'

services:
    postgres:
        image: postgres:9.6
        ports:
            - '5432:5432'
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: coffee
            POSTGRES_PASSWORD: qwerty123
            POSTGRES_DB: coffee

    payments:
        image: rodolpheche/wiremock
        ports:
            - '8080'
        volumes:
            - ./payments:/home/wiremock/mappings
