version: '3'

volumes:
  grafana_lib: {}
  prometheus_data: {}

services:

  reception:
    image: italolelis/reception
    ports:
      - '9010:8080'
    environment:
      LOG_LEVEL: debug
      DATABASE_DSN: postgres://coffee:qwerty123@reception_db/reception?sslmode=disable
      EVENT_STREAM_DSN: amqp://rabbit/
      JAEGER_SERVICE_NAME: "reception"
      JAEGER_COLLECTOR_ENDPOINT: "http://localhost:14268/api/traces?format=jaeger.thrift"
      METRICS_SERVICE_NAME: "reception"

  #  barista:
  #    image: italolelis/reception
  #    environment:
  #      LOG_LEVEL: debug
  #      EVENT_STREAM_DSN: amqp://rabbit/
  #      JAEGER_SERVICE_NAME: "reception"
  #      JAEGER_COLLECTOR_ENDPOINT: "http://localhost:14268/api/traces?format=jaeger.thrift"
  #      METRICS_SERVICE_NAME: "reception"

  payments:
    image: rodolpheche/wiremock
    ports:
      - '8081'
    volumes:
      - ./payments:/home/wiremock/mappings

  reception_db:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: coffee
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: reception

  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  prometheus:
    image: prom/prometheus:v2.1.0
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ${PWD}/configs/prometheus/prometheus.yaml:/prometheus.yaml
    command:
      - '--config.file=/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:5.1.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_lib:/var/lib/grafana
      - ${PWD}/configs/prometheus/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
